# Generated by Django 3.0.7 on 2020-07-01 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0003_auto_20200701_1620'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='type',
            field=models.CharField(choices=[('appetizer', 'Appetizer'), ('main_course', 'Main Course'), ('garnish', 'Garnish'), ('desert', 'Desert')], default='main_course', max_length=50),
        ),
    ]
