# Generated by Django 3.0.7 on 2020-07-01 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0004_recipe_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='type',
            field=models.CharField(choices=[('Appetizer', 'Appetizer'), ('Main Course', 'Main Course'), ('Garnish', 'Garnish'), ('Desert', 'Desert')], default='main_course', max_length=50),
        ),
    ]
