# Generated by Django 3.0.7 on 2020-07-01 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0005_auto_20200701_1643'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='type',
            field=models.CharField(choices=[('Appetizer', 'Appetizer'), ('Main Course', 'Main Course'), ('Garnish', 'Garnish'), ('Desert', 'Desert')], default='Main Course', max_length=50),
        ),
    ]
