# Generated by Django 3.0.7 on 2020-07-01 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0006_auto_20200701_2158'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='image',
            field=models.ImageField(default='default_recipe.jpg', upload_to='recipe_imgs'),
        ),
    ]
