# Generated by Django 3.0.7 on 2020-07-02 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0008_auto_20200702_1805'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='type',
            field=models.CharField(choices=[('appetizer', 'Appetizer'), ('main_course', 'Main-Course'), ('garnish', 'Garnish'), ('desert', 'Desert')], default='Main-Course', max_length=50),
        ),
    ]
