# Generated by Django 3.0.7 on 2020-07-04 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0011_auto_20200703_1902'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='type',
            field=models.CharField(choices=[('Appetizer', 'Appetizer'), ('Main-Course', 'Main-Course'), ('Garnish', 'Garnish'), ('Desert', 'Desert'), ('Drink', 'Drink')], default='Main-Course', max_length=50),
        ),
    ]
